version: '3'

dotenv: ['.env'] # take variables from .env file

env:
  OK_COLOR: '\033[32;01m'
  NO_COLOR: '\033[0m'

tasks:
  default:
    cmds:
      - task --list-all
  lint:
    cmds:
      - golangci-lint run -c .golangci.yml
  test:
    cmds:
      - go list ./consumer/... | grep -v /mock_ > packages.out
      - go test -gcflags=-l -covermode=atomic -coverprofile=coverage.tmp -race $(cat packages.out)
      - cat coverage.tmp | grep -v mock_ > coverage.out
      - rm coverage.tmp
  update-deps:
    desc: Update dependencies
    cmds:
      - go get -u -d ./...
  fumpt:
    desc: Gofumpt project files
    cmds:
      - find . -name '*.go' -type f -exec gofumpt -w {} +
  clean:
    desc: Clean up
    cmds:
      - go mod tidy
      - task: fumpt