global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Scrape metrics from OTEL collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 5s
    metrics_path: /metrics

  # Scrape metrics from SQS consumer application
  - job_name: 'sqs-consumer'
    static_configs:
      - targets: ['sqs-consumer:9464']  # Containerized SQS consumer application
    scrape_interval: 5s
    metrics_path: /metrics

  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']